Task_1_3_1
Ensell84/OOP pull request #2
Opened 2024-11-25 17:24 UTC by Ensell84

2024-12-08 15:45 UTC, Ensell84 commented
- [x]  Сделан  rebase лишнего коммита, который удалял Task_1_1_1
- [x] Исправлен последний warning Reviewdog-а

2024-12-17 08:25 UTC, shadrina requested changes

2024-12-17 08:25 UTC, shadrina commented on Task_1_3_1/src/main/java/ru/nsu/bondar/SubstringFinder.java
> +        if (filename == null || pattern == null) {
`@NotNull`

2024-12-17 08:25 UTC, shadrina commented on Task_1_3_1/src/test/java/ru/nsu/bondar/SubstringFinderTest.java
> +        int sizeInMb = 5000;
Попробуй дома 15

2024-12-24 07:19 UTC, Ensell84 commented
- [ ] Большой файл 15 Гб --> локально 4 мин 30 сек, в GithubActions < 3 мин

2024-12-24 08:54 UTC, shadrina approved these changes

2024-12-24 20:47 UTC, merged